### ISSUE TITLE
[12.0] helpdesk_mgmt_ticket_tree_recent - enable ticket sorting for tree view as kanban does

### ISSUE THREAD

**Issue by dalonsod** [solvosci/slv-helpdesk#23]
Hello,

I'd noticed that kanban sorting for tickets is quite different than tree sorting depending on instaled addons:

- Kanban makes order by priority, sequence and number (https://github.com/OCA/helpdesk/blob/12.0/helpdesk_mgmt/models/helpdesk_ticket.py#L10 , the model default), which is useful for re-ordering purposes.
- Tree view should do the same.
- But, if `helpdesk_mgmt_ticket_tree_recent` is installed, the default behavior is replaced by a date sorting.

Is it possible to make a `helpdesk_mgmt_ticket_tree_recent` addon improvement to avoid this, if needed? We'd need optionally disabling it by user; then, if a user with this option disabled enables grouping by stage in `tree` view, he'll actually see the same sorting than kanban view.

@ChristianSantamaria @lmiguens-solvos what do you think?

**Comment by lmiguens-solvos** [comment]
> Hello,
> 
> I'd noticed that kanban sorting for tickets is quite different than tree sorting depending on instaled addons:
> 
> * Kanban makes order by priority, sequence and number (https://github.com/OCA/helpdesk/blob/12.0/helpdesk_mgmt/models/helpdesk_ticket.py#L10 , the model default), which is useful for re-ordering purposes.
> * Tree view should do the same.
> * But, if `helpdesk_mgmt_ticket_tree_recent` is installed, the default behavior is replaced by a date sorting.
> 
> Is it possible to make a `helpdesk_mgmt_ticket_tree_recent` addon improvement to avoid this, if needed? We'd need optionally disabling it by user; then, if a user with this option disabled enables grouping by stage in `tree` view, he'll actually see the same sorting than kanban view.
> 
> @ChristianSantamaria @lmiguens-solvos what do you think?

Hello,
I think it's a good idea.
Sorting by date of last modification does not provide anything for some users, and those would be the ones that would have this disabled. Furthermore, in the tree view you can finally always sort by date of last modification by clicking on the header of this data.

**Comment by dalonsod** [comment]
@ChristianSantamaria could you create a PR with this improvement?
- create a new group for enabling/disabling current feature, instead of forcing it for every user.
- By default, disabled.

**Comment by dalonsod** [comment]
Open #24

**Comment by dalonsod** [comment]
As #24 is merged, I'll close this
