### ISSUE TITLE
[12.0] New addon - ticket stages always fold on kanban view

### ISSUE THREAD

**Issue by dalonsod** [solvosci/slv-helpdesk#25]
An interesting feature for helpdesk should be the same as https://github.com/OCA/maintenance/tree/12.0/maintenance_equipment_always_fold , for tickets and stages instead of maintenance equipments and categories.

@lmiguens-solvos @ChristianSantamaria what do you think? When done, we could post it to OCA, as well.

**Comment by ChristianSantamaria** [comment]
Yes I think it's a good idea, I get on with it

**Comment by ChristianSantamaria** [comment]
I had not realized it before but apparently this option already exists in helpdesk https://github.com/OCA/helpdesk/blob/8e78b3e63c79756116f0b953649bdd8521132e85/helpdesk_mgmt/models/helpdesk_ticket_stage.py#L25

**Comment by dalonsod** [comment]
Oops, you're right. Closing this

**Comment by dalonsod** [comment]
One thing: if anyone wants to use it, be careful, because a stage could be shared across every company, so this change will be applied to all.
